export const standardSkills = {
  athletics: ['str', 'dex'],
  boating: ['str', 'con'],
  brawn: ['str', 'siz'],
  conceal: ['dex', 'pow'],
  customs: ['int', 'int', 40],
  dance: ['dex', 'cha'],
  deceit: ['int', 'cha'],
  drive: ['dex', 'pow'],
  endurance: ['con', 'con'],
  evade: ['dex', 'dex'],
  firstAid: ['int', 'dex'],
  influence: ['cha', 'cha'],
  insight: ['int', 'pow'],
  locale: ['int', 'int'],
  nativeTongue: ['int', 'cha', 40],
  perception: ['int', 'pow'],
  ride: ['dex', 'pow'],
  sing: ['cha', 'pow'],
  stealth: ['dex', 'int'],
  swim: ['str', 'con'],
  unarmed: ['str', 'dex'],
  willpower: ['pow', 'pow']
}

export const proSkills = {
  acting: ['cha', 'cha'],
  acrobatics: ['str', 'dex'],
  art: ['pow', 'cha'],
  astrogation: ['int', 'int'],
  bureaucracy: ['int', 'int'],
  commerce: ['int', 'cha'],
  comms: ['int', 'int'],
  computers: ['int', 'int'],
  courtesy: ['int', 'cha'],
  craft: ['dex', 'int'],
  culture: ['int', 'int'],
  demolitions: ['int', 'pow'],
  disguise: ['int', 'cha'],
  electronics: ['dex', 'int'],
  engineering: ['int', 'int'],
  forgery: ['dex', 'int'],
  gambling: ['int', 'pow'],
  healing: ['int', 'pow'],
  language: ['int', 'cha'],
  literacy: ['int', 'int'],
  lockpicking: ['dex', 'dex'],
  lore: ['int', 'int'],
  mechanisms: ['dex', 'int'],
  musicianship: ['dex', 'cha'],
  navigation: ['int', 'pow'],
  oratory: ['pow', 'cha'],
  pilot: ['dex', 'int'],
  politics: ['int', 'cha'],
  research: ['int', 'pow'],
  science: ['int', 'int'],
  seamanship: ['int', 'con'],
  seduction: ['int', 'cha'],
  sensors: ['int', 'pow'],
  sleight: ['dex', 'cha'],
  streetwise: ['pow', 'cha'],
  survival: ['con', 'pow'],
  teach: ['int', 'cha'],
  track: ['int', 'con']
}
