// Fight
export const FIGHT_START = 'FIGHT_START'
export const FIGHT_END = 'FIGHT_END'
export const FIGHT_SELECTION_CHARACTER_ADD = 'FIGHT_SELECTION_CHARACTER_ADD'
export const FIGHT_SELECTION_FOE_ADD = 'FIGHT_SELECTION_FOE_ADD'
export const FIGHT_SELECTION_CHARACTER_REMOVE = 'FIGHT_SELECTION_CHARACTER_REMOVE'
export const FIGHT_SELECTION_VALIDATE = 'FIGHT_SELECTION_VALIDATE'
export const TURN_NEXT = 'TURN_NEXT'

// fight actions
export const FIGHT_CHAR_END_TURN = 'FIGHT_CHAR_END_TURN'
export const FIGHT_CHAR_DELAY = 'FIGHT_CHAR_DELAY'

// Characters
export const CHAR_GET = 'CHAR_GET'
