// Fight
export const FIGHT_START = 'FIGHT_START'
export const FIGHT_END = 'FIGHT_END'
export const FIGHT_SELECTION_CHARACTER_ADD = 'FIGHT_SELECTION_CHARACTER_ADD'
export const FIGHT_SELECTION_FOE_ADD = 'FIGHT_SELECTION_FOE_ADD'
export const FIGHT_SELECTION_CHARACTER_REMOVE = 'FIGHT_SELECTION_CHARACTER_REMOVE'
export const FIGHT_SELECTION_VALIDATE = 'FIGHT_SELECTION_VALIDATE'
export const ROUND_NEXT = 'ROUND_NEXT'

// fight actions
export const SKILL_USE = 'SKILL_USE'
export const ACTION_USE = 'ACTION_USE'
export const ACTION_ATTACK = 'ACTION_ATTACK'
export const ACTION_MOVE = 'ACTION_MOVE'
export const ACTION_END_TURN = 'ACTION_END_TURN'
export const ACTION_DELAY_TURN = 'ACTION_DELAY_TURN'

// Characters
export const CHAR_GET = 'CHAR_GET'
