export { default as armor } from './chest-armor.svg'
export { default as damage } from './light-sabers.svg'
export { default as dice } from './rolling-dices.svg'
export { default as life } from './techno-heart.svg'
export { default as magic } from './aura.svg'
export { default as target } from './crosshair.svg'

// for equipment
export { default as back } from './back.svg'
export { default as belt } from './belt.svg'
export { default as chest } from './chest.svg'
export { default as feet } from './feet.svg'
export { default as hands } from './hands.svg'
export { default as head } from './head.svg'
export { default as legs } from './legs.svg'
export { default as neck } from './neck.svg'
export { default as offhand } from './offhand.svg'
export { default as ring1 } from './ring1.svg'
export { default as ring2 } from './ring2.svg'
export { default as shoulders } from './shoulders.svg'
export { default as weapon1 } from './weapon1.svg'
export { default as weapon2 } from './weapon2.svg'
