export default {
  kind: 'hero',
  attributes: {
    str: 3,
    dex: 3,
    pow: 3,
    con: 3,
    cha: 3,
    siz: 8,
    int: 8
  },
  standardSkills: {
    athletics: 0,
    boating: 0,
    brawn: 0,
    conceal: 0,
    customs: 0,
    dance: 0,
    deceit: 0,
    drive: 0,
    endurance: 0,
    evade: 0,
    firstAid: 0,
    influence: 0,
    insight: 0,
    locale: 0,
    nativeTongue: 0,
    perception: 0,
    ride: 0,
    sing: 0,
    stealth: 0,
    swim: 0,
    unarmed: 0,
    willpower: 0
  },
  proSkills: {
    acting: 0,
    acrobatics: 0,
    art: 0,
    astrogation: 0,
    bureaucracy: 0,
    commerce: 0,
    comms: 0,
    computers: 0,
    courtesy: 0,
    craft: 0,
    culture: 0,
    demolitions: 0,
    disguise: 0,
    electronics: 0,
    engineering: 0,
    forgery: 0,
    gambling: 0,
    healing: 0,
    language: 0,
    literacy: 0,
    lockpicking: 0,
    lore: 0,
    mechanisms: 0,
    musicianship: 0,
    navigation: 0,
    oratory: 0,
    pilot: 0,
    politics: 0,
    research: 0,
    science: 0,
    seamanship: 0,
    seduction: 0,
    sensors: 0,
    sleight: 0,
    streetwise: 0,
    survival: 0,
    teach: 0,
    track: 0
  },
  talents: [],
  skills: [],
  equipment: {
    chest: { armor: 1 }
  },
  inventory: {
    lifePotion: {
      name: 'Potion de vie',
      quantity: 1,
      cost: 2,
      recovery: 20
    }
  },
  credits: 500
}
