// cf: http://app.fontastic.me/#customize/pjR3s7CAgaZ4fRuBYftKZ8
const weapon = [
  // others
  'monkey-wrench',
  'broken-bottle',
  'crowbar',
  'umbrella-bayonet',
  // hand weapons
  'steel-claws',
  // swords
  'dagger',
  'sword',
  'bone-knife',
  'sai',
  'knife-thrust',
  'spiral-thrust',
  'katana',
  'machete',
  'glaive',
  'relic-blade',
  'broad-dagger',
  'gladius',
  'two-handed-sword',
  'rusty-sword',
  'shard-sword',
  'piercing-sword',
  'croc-sword',
  'sacrificial-dagger',
  'stiletto',
  'fragmented-sword',
  'lightning-saber',
  // axes
  'hatchet',
  'stone-axe',
  'wood-axe',
  'fire-axe',
  'sharp-axe',
  'war-axe',
  'battered-axe',
  'battle-axe',
  'tomahawk',
  // maces
  'bone-mace',
  'nunchaku',
  'baseball-bat',
  '3d-hammer',
  'toy-mallet',
  'baton',
  'bo',
  'bolas',
  'flail',
  'spiked-bat',
  'spiked-mace',
  'telescopic-baton',
  'flanged-mace',
  'kusarigama',
  // spears
  'barbed-spear',
  'stone-spear',
  'sharp-halberd',
  'halberd',
  'harpoon-trident',
  'scythe',
  'trident',
  'magic-trident',
  'flaming-trident',
  // staffs
  'wizard-staff',
  'skull-staff',
  'caduceus',
  'rod-of-asclepius',
  'fairy-wand',
  'crystal-wand',
  'orb-wand',
  'lunar-wand',
  // ranged
  'shuriken',
  'slingshot',
  'boomerang',
  'armored-boomerang',
  'pocket-bow',
  'high-shot',
  'crossbow',
  // fire weapons
  'revolver',
  'famas',
  'mp5',
  'tec-9',
  'flamethrower',
  'lee-enfield',
  'ak47',
  'p90',
  'walther-ppk'
]
const offhand = [
  'broken-shield',
  'checked-shield',
  'cracked-shield',
  'crenulated-shield',
  'cross-shield',
  'edged-shield',
  'eye-shield',
  'fire-shield',
  'ice-shield',
  'layered-armor',
  'lightning-shield',
  'magic-shield',
  'roman-shield',
  'rosa-shield',
  'round-shield',
  'shield',
  'skull-shield',
  'slashed-shield',
  'templar-shield',
  'trident-shield',
  'vibrating-shield',
  'viking-shield',
  'winged-shield',
  'zebra-shield',
  'dragon-orb',
  'frozen-orb',
  'extraction-orb',
  'orbit',
  'smoking-orb',
  'unstable-orb',
  'quiver'
]
const head = [
  'android-mask',
  'bandit',
  'barbute',
  'black-knight-helm',
  'brutal-helm',
  'cracked-helm',
  'crested-helmet',
  'dwarf-helmet',
  'dwarf-king',
  'elf-helmet',
  'galea',
  'gauls-helm',
  'heavy-helm',
  'helmet',
  'horned-helm',
  'imperial-crown',
  'jester-hat',
  'jewel-crown',
  'light-helm',
  'mecha-mask',
  'outback-hat',
  'overlord-helm',
  'pilgrim-hat',
  'pointy-hat',
  'pope-crown',
  'pschent-double-crown',
  'robin-hood-hat',
  'samurai-helmet',
  'spartan-helmet',
  'trap-mask',
  'viking-helmet',
  'visored-helm',
  'war-bonnet',
  'warlock-hood'
]
const shoulders = [
  'dorsal-scales',
  'pauldrons',
  'shoulders',
  'shoulder-scales',
  'spiked-shoulders',
  'stegosaurus-scales'
]
const back = ['back']
const chest = [
  't-shirt',
  'shirt',
  'fur-shirt',
  'ample-dress',
  'dress',
  'large-dress',
  'armor-vest',
  'breastplate',
  'chest',
  'chain-mail',
  'lamellar',
  'leather-armor',
  'leather-vest',
  'ninja-armor',
  'plastron',
  'robe',
  'shoulder-armor'
]
const hands = ['bracer', 'bracers', 'claws', 'gauntlet', 'gloves', 'mechanical-arm', 'metal-hand', 'skeletal-hand']
const belt = ['belt', 'black-belt', 'leather-belt', 'skull-signet']
const legs = ['trousers', 'armored-pants', 'legs', 'loincloth', 'metal-skirt', 'robot-leg', 'skirt']
const feet = [
  'sonic-shoes',
  'boots',
  'chelsea-boot',
  'cowboy-boot',
  'fur-boot',
  'heavy-boots',
  'leather-boot',
  'rubber-boot',
  'steeltoe-boots',
  'tabi-boot',
  'wooden-clogs'
]
const neck = [
  'amulet',
  'claw-string',
  'emerald-necklace',
  'gem-chain',
  'gem-necklace',
  'gem-pendant',
  'heart-necklace',
  'pearl-necklace',
  'primitive-necklace',
  'torc',
  'tribal-pendant'
]
const ring = ['ring1', 'ring2', 'fire-ring', 'skull-ring', 'diamond-ring', 'big-diamond-ring']
export default {
  equipment: {
    weapon,
    offhand,
    head,
    shoulders,
    back,
    chest,
    hands,
    belt,
    legs,
    feet,
    neck,
    ring
  },
  usable: ['potion', 'health-potion', 'magic-potion', 'potion-ball', 'rope-coil', 'skeleton-key'],
  misc: ['rolling-dice', 'aura', 'target', 'crossed-swords', 'techno-heart', 'half-heart', 'rupee', 'pencil']
}
